# Generated by Django 4.0.6 on 2025-04-17 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuthGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
            ],
            options={
                'db_table': 'auth_group',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthGroupPermissions',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_group_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('codename', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'auth_permission',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('is_superuser', models.IntegerField()),
                ('username', models.CharField(max_length=150, unique=True)),
                ('first_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(max_length=150)),
                ('email', models.CharField(max_length=254)),
                ('is_staff', models.IntegerField()),
                ('is_active', models.IntegerField()),
                ('date_joined', models.DateTimeField()),
            ],
            options={
                'db_table': 'auth_user',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserGroups',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_user_groups',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserUserPermissions',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_user_user_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Chambre',
            fields=[
                ('idchambre', models.AutoField(primary_key=True, serialize=False)),
                ('numero', models.CharField(max_length=11)),
                ('type', models.CharField(max_length=45)),
                ('description', models.CharField(max_length=45)),
                ('prix', models.FloatField()),
                ('maison', models.CharField(max_length=10)),
                ('chambre', models.CharField(max_length=10)),
                ('etage', models.IntegerField()),
                ('local', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'chambre',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('idclient', models.AutoField(primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=255)),
                ('numid', models.CharField(blank=True, max_length=30, null=True)),
                ('genre', models.CharField(blank=True, max_length=10, null=True)),
                ('datenaiss', models.DateField(blank=True, null=True)),
                ('adresse', models.CharField(blank=True, max_length=255, null=True)),
                ('email', models.CharField(blank=True, max_length=205, null=True)),
                ('telephone', models.CharField(blank=True, max_length=45, null=True)),
                ('profession', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'client',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoAdminLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_time', models.DateTimeField()),
                ('object_id', models.TextField(blank=True, null=True)),
                ('object_repr', models.CharField(max_length=200)),
                ('action_flag', models.PositiveSmallIntegerField()),
                ('change_message', models.TextField()),
            ],
            options={
                'db_table': 'django_admin_log',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoContentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_label', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'django_content_type',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoMigrations',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('app', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('applied', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_migrations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoSession',
            fields=[
                ('session_key', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('session_data', models.TextField()),
                ('expire_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_session',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Employe',
            fields=[
                ('idemploye_cadeau', models.AutoField(primary_key=True, serialize=False)),
                ('matricule', models.CharField(max_length=45, unique=True)),
                ('nom_ar', models.CharField(max_length=255)),
                ('service', models.CharField(max_length=255)),
                ('nom_fr', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'employe',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Facture',
            fields=[
                ('idfacture', models.AutoField(primary_key=True, serialize=False)),
                ('idres', models.IntegerField(blank=True, null=True)),
                ('idheb', models.IntegerField(blank=True, null=True)),
                ('date', models.DateField()),
                ('njours', models.IntegerField(blank=True, null=True)),
                ('statut', models.CharField(max_length=45)),
                ('ln', models.CharField(blank=True, max_length=45, null=True)),
            ],
            options={
                'db_table': 'facture',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='HbgRecap',
            fields=[
                ('idhebergement_recap', models.AutoField(primary_key=True, serialize=False)),
                ('idhebg', models.IntegerField(db_column='idHebg')),
                ('idresv', models.IntegerField(blank=True, db_column='idResv', null=True)),
                ('etablissement', models.CharField(max_length=512)),
                ('dateh', models.DateField(db_column='dateH')),
                ('dates', models.DateField(db_column='dateS')),
                ('nuitee', models.IntegerField()),
                ('capacite', models.IntegerField()),
                ('statut', models.CharField(max_length=255)),
                ('nc', models.CharField(db_column='nC', max_length=45)),
                ('statp', models.CharField(db_column='statP', max_length=45)),
                ('moyen', models.CharField(max_length=255)),
                ('codeclient', models.CharField(blank=True, max_length=45, null=True)),
                ('demandeur', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'hbg_recap',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Hebergement',
            fields=[
                ('idhebergement', models.IntegerField()),
                ('roomnum', models.CharField(max_length=20)),
                ('nomclient', models.CharField(max_length=255)),
                ('note', models.CharField(blank=True, max_length=2000, null=True)),
                ('reservid', models.IntegerField(blank=True, null=True)),
                ('dateheberg', models.DateField()),
                ('datesortie', models.DateField()),
                ('nuitee', models.IntegerField()),
                ('statutchambre', models.CharField(max_length=50)),
                ('type', models.CharField(blank=True, max_length=20, null=True)),
                ('etablissement', models.CharField(max_length=1024)),
                ('sujet', models.CharField(blank=True, max_length=512, null=True)),
                ('priseencharge', models.CharField(blank=True, max_length=45, null=True)),
                ('categorie', models.CharField(blank=True, max_length=25, null=True)),
                ('demandeur', models.CharField(max_length=100)),
                ('ncourrierh', models.IntegerField()),
                ('statuthebg', models.CharField(blank=True, max_length=45, null=True)),
                ('capacite', models.IntegerField(blank=True, null=True)),
                ('slno', models.AutoField(primary_key=True, serialize=False)),
                ('capgroup', models.IntegerField()),
                ('compt', models.IntegerField()),
                ('statpay', models.CharField(db_column='statPay', max_length=45)),
                ('moyen', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'hebergement',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Payement',
            fields=[
                ('idpayement', models.AutoField(primary_key=True, serialize=False)),
                ('code_client', models.CharField(max_length=25)),
                ('statutpay', models.CharField(max_length=11)),
                ('resid', models.IntegerField(blank=True, null=True)),
                ('hebgid', models.IntegerField(blank=True, null=True)),
                ('datepay', models.DateField(blank=True, null=True)),
                ('montant', models.CharField(max_length=13)),
                ('note', models.CharField(blank=True, max_length=1024, null=True)),
                ('idencaisse', models.CharField(max_length=125)),
                ('nencaisse', models.CharField(max_length=13)),
                ('dateencaisse', models.DateField()),
                ('ln', models.CharField(blank=True, max_length=45, null=True)),
                ('numpay', models.IntegerField(db_column='numPay')),
            ],
            options={
                'db_table': 'payement',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Pointage',
            fields=[
                ('idpointage', models.AutoField(primary_key=True, serialize=False)),
                ('annee', models.TextField()),
                ('mois', models.DateTimeField()),
                ('du', models.DateTimeField()),
                ('au', models.DateTimeField()),
                ('presence', models.IntegerField()),
                ('absence', models.IntegerField()),
            ],
            options={
                'db_table': 'pointage',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('idreservation', models.IntegerField(primary_key=True, serialize=False)),
                ('administration', models.CharField(max_length=255)),
                ('coordinateur', models.CharField(max_length=250)),
                ('codeclient', models.CharField(blank=True, max_length=250, null=True)),
                ('description', models.CharField(max_length=250)),
                ('datedeb', models.DateField()),
                ('datefin', models.DateField()),
                ('nbrejours', models.IntegerField()),
                ('logement', models.IntegerField(blank=True, null=True)),
                ('nbrepersonne', models.IntegerField()),
                ('salle', models.CharField(max_length=95)),
                ('typeh', models.CharField(blank=True, max_length=70, null=True)),
                ('piecejointe', models.TextField(blank=True, null=True)),
                ('noter', models.CharField(blank=True, max_length=2000, null=True)),
                ('lieu', models.CharField(blank=True, max_length=255, null=True)),
                ('ncourrier', models.IntegerField()),
                ('statutres', models.CharField(max_length=45)),
                ('capreservation', models.IntegerField()),
                ('nbrepcafe', models.IntegerField()),
                ('nbredej', models.IntegerField()),
                ('statres', models.CharField(db_column='statRes', max_length=45)),
                ('moyen', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'reservation',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Restauration',
            fields=[
                ('idrestauration', models.AutoField(primary_key=True, serialize=False)),
                ('type', models.CharField(blank=True, max_length=45, null=True)),
                ('prix', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'restauration',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Salle',
            fields=[
                ('idsalle', models.AutoField(primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=95)),
                ('prix', models.FloatField()),
                ('local', models.CharField(max_length=125)),
            ],
            options={
                'db_table': 'salle',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('idsession', models.AutoField(primary_key=True, serialize=False)),
                ('pseudo', models.CharField(max_length=45)),
                ('connexion', models.DateTimeField(blank=True, null=True)),
                ('deconnexion', models.DateTimeField(blank=True, null=True)),
                ('ipadd', models.CharField(blank=True, max_length=45, null=True)),
                ('hostname', models.CharField(blank=True, max_length=45, null=True)),
            ],
            options={
                'db_table': 'session',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Statut',
            fields=[
                ('idstatut', models.AutoField(primary_key=True, serialize=False)),
                ('statut', models.CharField(max_length=45)),
                ('num_conge', models.CharField(blank=True, max_length=45, null=True)),
                ('num_autorisation', models.CharField(blank=True, max_length=45, null=True)),
                ('remarque', models.CharField(blank=True, max_length=45, null=True)),
                ('idpointage', models.IntegerField()),
            ],
            options={
                'db_table': 'statut',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(blank=True, max_length=75, null=True)),
                ('prenom', models.CharField(blank=True, max_length=75, null=True)),
                ('pseudo', models.CharField(blank=True, max_length=45, null=True)),
                ('password', models.CharField(blank=True, max_length=45, null=True)),
                ('role', models.CharField(blank=True, max_length=45, null=True)),
                ('email', models.CharField(blank=True, max_length=255, null=True)),
                ('is_staff', models.IntegerField(blank=True, null=True)),
                ('is_active', models.IntegerField(blank=True, null=True)),
                ('date_joined', models.DateField(blank=True, null=True)),
                ('last_updated', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'user',
                'managed': False,
            },
        ),
    ]
