# Generated by Django 4.0.6 on 2025-04-14 09:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Benefice',
            fields=[
                ('id_benefice', models.AutoField(primary_key=True, serialize=False)),
                ('critere_logement', models.IntegerField(blank=True, null=True)),
                ('critere_repas', models.IntegerField(blank=True, null=True)),
                ('critere_bourse', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'benefice',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Chercheur',
            fields=[
                ('id_chercheur', models.AutoField(primary_key=True, serialize=False)),
                ('num_cin', models.IntegerField()),
                ('id_ira', models.IntegerField()),
                ('email', models.CharField(blank=True, max_length=255, null=True)),
                ('statut', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'chercheur',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Destination',
            fields=[
                ('id_destination', models.AutoField(primary_key=True, serialize=False)),
                ('libelle', models.CharField(blank=True, max_length=1024, null=True)),
                ('pays', models.CharField(blank=True, max_length=1024, null=True)),
                ('ville', models.CharField(blank=True, max_length=1024, null=True)),
            ],
            options={
                'db_table': 'destination',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Etudiant',
            fields=[
                ('id_etudiant', models.AutoField(primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=255)),
                ('date_naissannce', models.DateField()),
                ('lieu_naissance', models.CharField(max_length=255)),
                ('num_identite', models.IntegerField()),
                ('email', models.CharField(blank=True, max_length=255, null=True)),
                ('telephone', models.CharField(blank=True, max_length=255, null=True)),
                ('adresse', models.CharField(blank=True, max_length=255, null=True)),
                ('statut', models.CharField(choices=[('طالب', 'طالب'), ('طالبة', 'طالبة')], max_length=255)),
                ('filiere', models.CharField(choices=[('دكتوراه', 'دكتوراه'), ('ماجيستير', 'ماجيستير')], max_length=255)),
                ('niveau', models.CharField(choices=[('الأولى', 'الأولى'), ('الثانية', 'الثانية'), ('الثالثة', 'الثالثة'), ('الرابعة', 'الرابعة'), ('الخامسة', 'الخامسة')], max_length=255)),
            ],
            options={
                'db_table': 'etudiant',
                'managed': True,
                'unique_together': {('nom', 'prenom', 'num_identite')},
            },
        ),
        migrations.CreateModel(
            name='Stage',
            fields=[
                ('id_stage', models.AutoField(primary_key=True, serialize=False)),
                ('titre', models.CharField(blank=True, max_length=255, null=True)),
                ('sujet', models.CharField(blank=True, max_length=1024, null=True)),
                ('date_aller', models.DateField(blank=True, null=True)),
                ('date_retour', models.DateField(blank=True, null=True)),
                ('id_benefice', models.ForeignKey(db_column='id_benefice', on_delete=django.db.models.deletion.DO_NOTHING, to='stage.benefice')),
                ('id_chercheur', models.ForeignKey(blank=True, db_column='id_chercheur', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='stage.chercheur')),
                ('id_destination', models.ForeignKey(db_column='id_destination', on_delete=django.db.models.deletion.DO_NOTHING, to='stage.destination')),
                ('id_etudiant', models.ForeignKey(blank=True, db_column='id_etudiant', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='stage.etudiant')),
            ],
            options={
                'db_table': 'stage',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Bourse',
            fields=[
                ('id_bourse', models.AutoField(primary_key=True, serialize=False)),
                ('type_bourse', models.CharField(blank=True, max_length=255, null=True)),
                ('prise_en_charge', models.CharField(blank=True, max_length=1024, null=True)),
                ('montant_total', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
                ('frais_transport', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
                ('frais_participation', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
                ('date_attribution', models.DateField(blank=True, null=True)),
                ('id_stage', models.ForeignKey(db_column='id_stage', on_delete=django.db.models.deletion.DO_NOTHING, to='stage.stage')),
            ],
            options={
                'db_table': 'bourse',
                'managed': True,
            },
        ),
    ]
